---
- hosts: k8s-workers

  tasks:
          - ping: ~

          - name: Update APT
            become: true
            apt:
                    update_cache: yes

          - name: Upgrade
            become: true
            apt:
                    upgrade: dist
...
